### ISSUE TITLE
libmixed.so built for android

### ISSUE THREAD

**Issue by Gleefre** [Shirakumo/cl-mixed#13]
Hello!

I have built the libmixed, you can find it here: https://github.com/Gleefre/android-build-libmixed/releases/tag/draft-build
I'm not sure if all the libraries were built properly, so I've attached build logs.

I am not sure how exactly to place them though, since there are 4 officially supported to this moment CPU architectures for android. So I'll leave it to you.

I also have only tested the `arm64-v8a` and `x86_64` versions of the library.

Have a nice day :)

**Comment by Shinmera** [comment]
Included as per [0f4260b](https://github.com/Shirakumo/cl-mixed/commit/0f4260bf4b3b94326aabbf8c7b772e5ce47e4bbe)

**Comment by Gleefre** [comment]
Hm, was this supposed to replace `lin-arm64-libmixed.so`?
Also, why not to create a separate `:android` section in definition of the library.

**Comment by Gleefre** [comment]
I have open a PR https://github.com/Shirakumo/cl-mixed/pull/15 .

**Comment by Shinmera** [comment]
Android is based on linux, and the libraries only depend on glibc, so there shouldn't be a need for a separate branch or release.

**Comment by Gleefre** [comment]
I don't know technical details, but android is only based on linux. Android libraries / libux libraries are not compatible.
Currently I get this on x86_64 emulator:
```lisp
Unable to load any of the alternatives:
   ("libmixed.so.2" "libmixed2.so" "libmixed.so"
    "lin-amd64-libmixed.so")
   [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]
```

**Comment by Shinmera** [comment]
Hrm, that's quite annoying.
