### ISSUE TITLE
Can't build recently - not sure what changed

### ISSUE THREAD

**Issue by quicklisp** [Shirakumo/cl-mixed#4]
When building today I get this:

```
Unhandled LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A380D3}>: Unable to load any of the alternatives:
   ("libmixed.so.2" "libmixed2.so" "libmixed.so" "lin-amd64-libmixed.so")
```

Is this the result of a recent source update? Is it possible the build environment changed instead somehow? How can I get libmixed?

**Comment by Shinmera** [comment]
Hmm. The library is bundled with the repo (see the static/ directory). Not sure why it would fail to find it.

**Comment by quicklisp** [comment]
More detail: when digging into the low-level calls, I get the error
"/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found, as
required by <path to the static/ shared library>"

I'm using Debian 10 for test builds.

**Comment by Shinmera** [comment]
Ah, that's helpful. I thought I had taken care of the glibc versioning stuff, but I guess I must not have got it down quite right. Will look into it tomorrow.

**Comment by Shinmera** [comment]
Should be good now, tested it successfully on a lower version of linux.
