### ISSUE TITLE
Github Pages missing

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Shirakumo/cl-mixed#5]
In both the project description and from a link in [harmony](https://github.com/Shirakumo/harmony) there's a link to the 'cl-mixed github pages' aka https://shirakumo.github.io/cl-mixed/ but it looks like this repo isn't set up with one. 

Was it removed, maybe?

**Comment by Shinmera** [comment]
Ah yeah, didn't put them back up after the rewrite.

**Comment by Shinmera** [comment]
I've pushed some bare-bones staple docs so the sites are at least live again. Will see if I find the time to write some better docs soon.

**Comment by Zulu-Inuoe** [comment]
I wouldn't stress on that too much. I think even a barebones doc is better than a 404.

Thanks!
